services:
  config:
    image: pawandvdockerid/config-repo:vconfig.1.0
    hostname: config
    volumes:
      - ./config-data:/var/config-data
    environment:
      - JAVA_OPTS=
         -Dspring.cloud.config.server.native.searchLocations=/var/config-data
    expose:
      - 8888
    networks:
      - ms-network
    ports:
      - 8888
  eureka:
    image: pawandvdockerid/eureka-repo:veureka.1.0
    hostname: eureka
    expose:
      - 8761
    ports:
      - 8761:8761
    depends_on:
      - config
    environment:
      - CONFIG_SERVER_URL=http://config:8888/
    networks:
      - ms-network
  portfolio-service:
    image: pawandvdockerid/portfolio-repo:vportfolio.1.0
    hostname: portfolio-service
    depends_on:
      - eureka
      - config
    environment:
      - CONFIG_SERVER_URL=http://config:8888/
      - EUREKA_SERVER=http://eureka:8761/eureka
    networks:
      - ms-network
    expose:
      - 9094
    ports:
      - 9094:9094
networks:
    ms-network:
        driver: bridge